### ISSUE TITLE
Server Crash When Quitting During Combat

### ISSUE THREAD

**Issue by BetaNepZ753** [WildToastyMop/CombatLog#8]
Everything was working flawlessly until I added CombatLog.

Now when I disconnect during Combat the WHOLE SERVER crashes. I dunno why.

I can provide any files needed for in depth assistance, thanks in advance.

**Comment by WildToastyMop** [comment]
Could you send the crashlog/latest log I think I know what the issue is but want to make sure I'll try to get it fixed soon whenever I have time

**Comment by BetaNepZ753** [comment]
I will attach all related files to help you getting it fixed asap, ty! <3

[debug.log](https://github.com/WildToastyMop/CombatLog/files/10690400/debug.log)
[latest.log](https://github.com/WildToastyMop/CombatLog/files/10690401/latest.log)
[crash-2023-02-08_22.31.07-server.txt](https://github.com/WildToastyMop/CombatLog/files/10690404/crash-2023-02-08_22.31.07-server.txt)

**Comment by BetaNepZ753** [comment]
When more or less do you think It'll be ready? I'm hosting a MC server and we are all hoping for the mod to be ready to use so we can add it to our mod list hehe
